# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Colorado Robotics
email: 

description: > # this means to ignore newlines until "baseurl:"
  Colorado Robotics aims to promote the development of advanced robotic technologies throughout the great state of Colorado.

baseurl: "" # the subpath of your site, e.g. /blog

 # the base hostname & protocol for your site, e.g. http://example.com
url: "https://coloradorobotics.org"

twitter_username: ColoRobots
github_username:  colorado-robotics

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# List of CO Meetups
meetups_list: &meetup_list
  - name: Boulder is for Robots
    url: https://www.meetup.com/BoulderIsForRobots/
  - name: Denver is for Robots
    url: https://www.meetup.com/Denver-Is-For-Robots/
  - name: Women in Robotics
    url: https://www.meetup.com/Women-in-Robotics-Boulder-Denver/
  - name: SHARC
    url: https://www.meetup.com/SHARC-Greater-Denver-Area-Robotics-Club/

header_links:
  - url: "/"
    type: link
    content: Home

  - content: Meetups
    type: dropdown
    items: *meetup_list         # Reuse the meetup list from above.

  - url: "/companies"
    type: link
    content: Companies

  # - url: "/youth"
  #   type: link
  #   content: ColoRoboKids

  # - url: "/research"
  #   type: link
  #   content: Research

  - url: "/sponsors"
    type: link
    content: Sponsors

social_links:
  - fa-icon: twitter
    url: "https://twitter.com/ColoRobots"

  - fa-icon: github
    url: "https://github.com/colorado-robotics"
